#+TOPICS: documentation
#+TAGS: qt gvle
#+DESCRIPTION: Qt Creator IDE to develop VLE, GVLE and plug-ins
#+DATE: 2017-03-29T11:07:51+02:00
#+TITLE: Qt Creator support

The [[https://github.com/vle-forge/vle/commit/d63ea94ac5f013c7ad7ada641483e78fe4e83c7c][master branch of VLE]] supports the [[https://www.qt.io/ide/][Qt Creator IDE]] via qmake. Qt Creator is a cross-platform IDE that includes productivity tools to speed up development time. Thanks to qmake, an Official support for MacOS10 should appear in future releases. Cmake remains the official project generator but qmake allow quick development of GVLE or GVLE's plug-ins.

* Installation

Install *Qt Creator* with Qt5 development files from your package manager on Linux or from the [[https://www.qt.io/ide/][Qt website]] on MacOS or Windows then, import VLE from the Git version control.

Be sure you have install libxml2 and the boost libraries and you may configure and build the VLE project.

** Linux

Under Linux, the default installation is done in the =$HOME/usr= prefix. To enable the use of the debugger, you may add a =make install= deployment pre-process and use the =$PREFIX/usr/bin/gvle= executable in the executable project settings.
